#!/usr/bin/php
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(-1);

require(__DIR__ . '/vendor/autoload.php');

try {

    $crawler = new \App\Infrastructure\Crawler(
        new \App\Infrastructure\Report\ArrayReportStorage()
    );

    $application = new App\CliApplication($crawler);
    $application->run();
    echo "\n";
    exit(0);

} catch (Exception $e) {

    echo 'ERROR: ' . $e->getMessage() . "\n";
    exit($e->getCode());

}