#!/usr/bin/php
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(-1);

require(__DIR__ . '/vendor/autoload.php');

$application = new App\Application();
$result = $application->run();
if ($result !== true) {
    echo $application->getError() . PHP_EOL;
}

exit(0);